### ISSUE TITLE
Visit Bug Hunting and v1.4

### ISSUE THREAD

**Issue by crazoter** [AY1920S1-CS2103-F10-1/main#182]
Issues resolved in PR #190:
- [x] #171: No need for sample data for current visit
- [x] #180, #176, #167, #163, #145, #144: Unable to replicate bug(s). Likely to have been fixed by datetime fix.
- [x] #179, #166: Fixed visit-start invalid format err. message
- [x] #154 : Fixed, overridden Index toString()
- [x] #158, #153, #152, #141: Update UG to properly display d/ instead of t/
- [x] #127: Updating UG to reflect that this feature is only in v2.0

Issues resolved by others:
- [x] #156: Todo: Francis to remove t/ option

Issues ignored:
- [x] #151: Works as expected.

Other PRs:
Impromptu Bug Fixes: #120, #121 
Documentation: #136, #137, #199

**Comment by cheongsiuhong** [comment]
8/8 !!! wow!!
