### ISSUE TITLE
Autocomplete Bug Hunting

### ISSUE THREAD

**Issue by crazoter** [AY1920S1-CS2103-F10-1/main#183]
- [x] #177 
- [x] #164
- [x] #161 (Document `exit` to `app-exit`)
- [x] #159, #146, #140, #122 (Document `find` to `pat-find`)
- [x] #138, #122 (Document `help` to `app-help`, or remove prefix)
- [x] #135 (Document `exit` to `app-exit`)
- [x] #128
- [x] #156: Todo: Francis to remove t/ option

**Comment by crazoter** [comment]
Sorry Francis, I realized the autocomplete includes `t/` for `visit-now-update` and I don't want to meddle with your increments. This should be a trivial fix, so could I trouble you to remove `t/`? Thanks.

**Comment by francislow** [comment]
Ok
