### ISSUE TITLE
Misc Bug Hunting

### ISSUE THREAD

**Issue by crazoter** [AY1920S1-CS2103-F10-1/main#186]
- [x] #160 (Update UG to indicate Tags can be used for gender or other purposes) @sandydays 
- [x] #157, #143, #139, #124 (Change code & UG to allow for same name) @gabrielchao 
- [x] #148 @crazoter (Error is as expected)
- [x] #147 @cheongsiuhong 
- [x] #129 @francislow

**Comment by cheongsiuhong** [comment]
5/5 !!!
