### ISSUE TITLE
Visit Management v1.3

### ISSUE THREAD

**Issue by crazoter** [AY1920S1-CS2103-F10-1/main#53]
User Stories Addressed:
#5, #6, #25 

Feature Description:
Add functionality that will allow users to manage visits.

Features Completed (v1.3)
- [X] Beginning a Visit (```visit-start p/PATIENT_INDEX```) (#75, 746087c)
- [X] Finishing a Visit (```visit-end```) (#75, 746087c)
- [X] Adding new Visit Commands (Start Visit, Display Visit, Update Visit Task, Set Visit Task as Done, Finish Visit) (#75)
- [X] Updating Current Visit (```visit-now-update [d/TASK_INDEX DETAIL]… [f/TASK_INDEX]… [uf/TASK_INDEX]… [r/REMARK]```), where t: Text, d: Done, ud: UnDone, r: Remark (#75)
- [X] Cancelling an on-going Visit (#88)
- [X] Implement OR delete `visit-now-show` (#88)
- [x] Marking multiple items of the current Visit's Todo list as done (#75)
- [X] Refactor `Person` and its commands to `Patient` and other refactoring such at the commands (#104)
- [X] Finish test cases and fix bugs (#93) (visit-now-update test cases omitted due to lack of time)

Features awaiting merging (v1.3):
- [x] Listing (and Viewing) finished visits of a patient (in `pat-list` or `pat-find`) (#89)
- [X] Enhancing the Visit UI Display (#108)

Feature Components in progress (v1.3):
- [X] Cleaning up User Guide (#82, #110)
- [X] Cleaning up Developer Guide (Do partial DG by Friday) (#90, #92, #110)

Feature Components (v1.3):
All done!

Changed Features:
- Listing (and Viewing) finished visits of a patient (in ```pat-view```) changed to listing and viewing in ```pat-list``` and ```pat-find```.

Feature Components (tentative unless time permits and/or design is appropriate):
- Deleting finished visits (Ruled out; visits should be archived and not deleted on nurse's whim)
- Managing Todo List Templates (Listing, adding, deleting, modifying todo list templates)
- Assigning a Todo List Template to a Patient

Notes: 
See https://github.com/AY1920S1-CS2103-F10-1/main/pull/75#pullrequestreview-304325034
