### ISSUE TITLE
Autocomplete feature v1.3

### ISSUE THREAD

**Issue by francislow** [AY1920S1-CS2103-F10-1/main#56]
Increment from #55 
Related to #33 #23 

**Feature Description:**
Add functionality to ease user interaction and understanding of system

**To complete:**
- [x] Implement auto-complete of object words set (such patient, vist)
- [x] Implement auto-complete of command words set (such list, sort, add-medcon)
- [x] Implement auto-complete of prefix words set (such t/, r/)
- [x] Implement index words to be suggested (and its logic for how many index to suggest)
- [x] Implement handlers to change word sets according to previous typed word in command textfield
(ie after command word is typed, either index or prefix set will be suggested in autocomplete panel)
- [x] Implement filters to update word set according to last typed word in command textfield
(ie words suggested must be compatible with the words that come before such as suggesting now-update only when previous word is visit)
- [x] redesign autocomplete panel

**To complete if time permits:**
- Press shift after selecting autocomplete word in the panel to see what its functionality
1. show the command functionality
2. show examples of how to use such a command
- Improve exception handling to tell the user which part of their command is wrongly inputted
- Press tab to complete word if only one autocomplete option is available
- store frequency of the usage of each suggested word and put higher usage words at the top of the suggested words
