### ISSUE TITLE
Visit Management v1.2

### ISSUE THREAD

**Issue by crazoter** [AY1920S1-CS2103-F10-1/main#62]
User Stories Addressed:
#5, #6, #25 

Feature Description:
Add functionality that will allow users to manage visits.

Feature Components Done (v1.2):
- [X] Adding Visit Components (Visit, VisitTodo, VisitTask model and JsonAdapted classes) (#68)
- [X] Adding associations with Visit Todos with Person (#68)
- [X] Adding Visit Todos to a patient (Implement like Tags) (```add [vt/VISIT_TODO]```) (#68)
- [X] Modifying Visit Todos of a patient (Implement like Tags) (```edit [vt/VISIT_TODO]```) (#68)
- [X] Removing Visit Todos to a patient (Implement like Tags) (```edit [vt/VISIT_TODO]```) (#68)
- [X] Displaying Visit Todos of a patient (```list``` or ```find```) (#68)
- [X] Adding associations of Visit with Patient (#68)

Feature Components Completed but shifted from v1.2 to v1.3 for integration
- [ ] Beginning a Visit (```visit-start p/PATIENT_INDEX```)
- [ ] Finishing a Visit (```visit-now-finish```)
- [ ] Adding new Visit Commands (Start Visit, Display Visit, Update Visit Task, Set Visit Task as Done, Finish Visit)
- [ ] Updating Current Visit (```visit-now-update [t/TASK_INDEX DETAIL] [d/TASK_INDEX] [ud/TASK_INDEX] [r/REMARK]```), where t: Text, d: Done, ud: UnDone, r: Remark

Feature Components In Todo (v1.2):

Deviations From Original Feature:
- [X] Displaying Visit UI (```visit-now-show```) Not needed because of tab system
- [X] Displaying Visit UI ```visit-now``` change to ```visit-now-show```
- [X] Displaying Visit Todos of a patient (```pat-view INDEX```)
- [X] Updating details of items of the current Visit's Task list (```visit-now-update TASK_INDEX d/DETAILS```)
- [X] Marking items of the current Visit's Task list as done/undone (```visit-now-done i/TASK_INDEX```)
- [X] Recording remarks (notes) of the current visit (```visit-now-remark r/REMARK```)

Other notes:
See https://github.com/AY1920S1-CS2103-F10-1/main/pull/68#discussion_r334264775

**Comment by crazoter** [comment]
Closed as v1.2 concludes
