### ISSUE TITLE
Appointment management

### ISSUE THREAD

**Issue by sandydays** [AY1920S1-CS2103-F10-1/main#64]
Related to User Stories #7

Features under consideration for implementation (some may move over to v2.0):
- [x] List all appointments nurses have scheduled, including reference to patient details, appointment time, date, and duration, and additional details of description associated with the appointment 
- [x] Display appointments as a list in order of the next earliest / upcoming appointments 
- [x] Find specific appointments by patient name.
- [x] Support recurring tasks (e.g. weekly appointments)
- [x] Add, delete, and edit appointments (handle invalid cases, etc.)
